### ISSUE TITLE
Some elements are not reskinned.

### ISSUE THREAD

**Issue by dwelden** [definite-d/PSG_Reskinner#4]
Frames and menus are not reskinned.

**Comment by definite-d** [comment]
Apologies for the late reply.

I assure you this has been fixed and will be available very soon.

**Comment by definite-d** [comment]
The fix is live from version 2.2.12, now available on GitHub and installable from PyPI using this command:

````shell
python -m pip install --upgrade PSG_Reskinner
````

Please check it out.

**Comment by dwelden** [comment]
Thanks for the quick response. Main menus are now reskinned, but the right-click context menus are still not updated.

**Comment by definite-d** [comment]
> Thanks for the quick response. Main menus are now reskinned, but the right-click context menus are still not updated.

Whoops... I forgot about the other menus... I'll work on it now.

**Comment by definite-d** [comment]
Right click menus have been fixed now, and will be released very soon.

**Comment by definite-d** [comment]
# Version 2.3.4.1

```shell
python -m pip install --upgrade PSG-Reskinner
```

The fix is live from version 2.3.4.1, along with multiple improvements:

- Right-click menus are now themed with thanks to @dwelden in a comment,
- Separators are now themed, 
- Reskinner no longer changes the current theme and now tries to leave no changes to object attributes behind (we were never here), 
- Checkboxes and Radios are now colored properly, 
- the demo now has a right-click menu, 
- the `exempt_element_keys` and `target_element_keys` feature (essentially element whitelisting) now works as expected,
- `animated_reskin()` now has 3 (importable) color interpolation modes: `RGB_INTERPOLATION`, `HUE_INTERPOLATION` and `HSV_INTERPOLATION`,
- Functions (even internal ones) in the module now state with the version they were first introduced within their docstrings.
- The `OptionMenu`'s active colors are no longer altered, just like regular PySimpleGUI behavior.
- A `reskin_background` argument has been introduced (especially useful when reskinning only a few elements; without it the background would be reskinned too)

**Comment by dwelden** [comment]
Unexpected behavior with scrollbars. Not sure what this part of the scrollbar is called, but the "trough" is not resetting properly. It appears to be one reset behind.

Initial display before reskinning:
![image](https://user-images.githubusercontent.com/11447810/201758484-9ab00dfb-e15d-432d-a22d-9a4ec30c8235.png)

Display after first reskinning:
![image](https://user-images.githubusercontent.com/11447810/201758579-1a2cb0bf-4c0c-4322-8229-a278e1867fab.png)

Display after second reskinning:
![image](https://user-images.githubusercontent.com/11447810/201758615-412b867a-32b7-40e5-86f5-bb6b960d337f.png)

**Comment by definite-d** [comment]
Thanks for the observation. I'll check it out.

**Comment by definite-d** [comment]
# Version 2.3.5

* The trough color of scrollbars have been fixed to update properly. It was caused by the "we were never here" flow, and I forgot to apply it only to troughs for some reason.

* Scrollable columns are now reskinned properly. PySimpleGUI creates columns in an entirely different way depending on whether they are scrollable or not.

* Some internal-only functions have been deprecated and will be removed in a subsequent minor release (v2.4).

* ttk Scrollbars have been improved, now relying on the `hsb_style_name` and `vsb_style_name` element attributes instead of brute-forcing style name combinations.

* Several other non-user-facing improvements and optimizations have been made as well.


### Side note:

After extensive testing, I discovered that the current approach to reskinning menus (re-declaring the entire menu definition thus creating a new menu from scratch) is not ideal, as Tkinter has a limit to the number of menus that can be created. I hit that mark around over 100 `animated` reskins.  In other words, the current implementation for menus of any kind is not sustainable for over 1000 reskins. Considering the fact that an animated reskin uses the reskin function not less than 10 times a second depending on the computing power, and it only happens if you actually use menus, you probably won't face that error in actual use with regular reskins. Since it exists though, I will fix it.

Enjoy.

**Comment by dwelden** [comment]
Thank you for the quick resolution.
